### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by nikolaradulov** [nikolaradulov/SLAMFuse#6]
- [x] A working SLAMBench container for the main app, to be tested with LSDSLAM
- [x] GUI working for SLAMBench container
- [x] Create mountable volume for lsdslam + documentation
- [x] Create mountable volume for dataset ICL_NUIM + documentation
- [x] Test SLAMBench + lsdslam volume + ICL_NUIM volume
- [x] Script for creating volumes for included algorithms + documentation
- [x] Script for creating volumes for included datasets + documentation

Week 17.07-23.07:
- [ ] Make ports for all the algorithms still supported/in existence: #9 
- [x]  Look into the best way of doing the distribution of the image and volumes
- [x] Implement sensors for LiDar/Event camera (at least 1 would be very good)
- [x] paper contributions
- [x] Write documentation and tutorials for existing parts

Week 24.07-30.07:
- [x] Cuda support in containers
- [x] Repair UZH for event cameras
- [x] test event sensors
- [x] Create Lidar Sensor
- [x] Lidar dataset

Week 31.07 - 06.08:
- [ ] Config file support
- [x] Introduction draft
- [ ] Experiments draft 
- [x] Event visualisation
- [x] .slam file for KITTI
- [x] automate the .slam generating process
- [x] cuda 

Week 07.08-13.08:

- [x]  Merge containarisation branch into main
- [x] write instructions for using the tool
- [x] fix linux gui for docker
- [x]  figure how events are transmited in ROS
- [ ] port EDS
- [x] run LOAM in slambench
- [x] LOAM: display pointcloud
- [ ] paper background
- [x] Add frame input to UZHFPV

**Comment by nikolaradulov** [comment]
- [ ] Make ports for all the algorithms still supported/in existence
- [ ]  Look into the best way of doing the distribution of the image and volumes
- [ ] Implement sensors for LiDar/Event camera (at least 1 would be very good)
- [ ] paper contributions
- [ ] Write documentation and tutorials for existing parts
